### ISSUE TITLE
If there was one thing you would do differently, what would it be?

### ISSUE THREAD

**Issue by zk433** [taniarascia/ama#11]
In the hindsight, is there something you would have done differently since you started learning web development?

**Comment by taniarascia** [comment]
Only one thing? There are so many things I'd do differently, it's hard to think of just one. But who knows what life would look like if I did any of those things? The one that comes to me most often is probably the fact that I never studied or practiced any sort of programming growing up. I spent a _lot_ of time with HTML and CSS growing up, but I never delved into PHP and JavaScript. One time I got a bit close with making a custom blog layout and using the blogger template language to loop through posts (which made WordPress somewhat familiar when I got to it), and I probably made a JavaScript alert at some point, but that's it. 

Three years ago, I had no idea what a loop or variable or if statement was. I remember looking at some PHP code as a child, trying to work with it for just a few minutes, and giving up when it was too hard. I was probably around 11 or 12 at that time, but I really wish I had started learning it back then. Now I'm trying to navigate through the basics of programming, the DOM, relatively simple concepts like uploading files and sending email, and usually frameworks abstract all that information away, but I insist on learning as much as I can the old fashioned way to have an idea of what I'm working with. 

It's easy for me to wish I had gone into web design and development instead of being a chef for nearly a decade, but I just don't know how my life would turn out, or if I would love and appreciate what I do now as much as I do.
