### ISSUE TITLE
What learning approach you follow while starting something new ?

### ISSUE THREAD

**Issue by Ayushverma8** [taniarascia/ama#4]
Excited to know :-)

**Comment by taniarascia** [comment]
Usually, I'll want to learn something because I'm interested in it and it keeps coming up. For example, I wanted to learn how to use Sass several years ago because I only knew how to use plain CSS, yet I was constantly seeing Sass in tutorials, CodePens, and various codebases. 

My learning approach, when I decide there's something in particular I want to learn, is trial and error. I typically don't watch any video tutorials on the subject or do any courses. I just try to create something very simple and get going with whatever the official documentation is. In the beginning, this often led to a rabbit hole of having to keep learning new things - I couldn't get a Gulp setup going until I figured out how to install Node, and I couldn't install Node until I had some basic command line knowledge, and so on.

It's not the best or most efficient way to learn, but I always document everything I need to know in the process so the next person can come along and hopefully find my website and solve their problem faster than I did.

I think what makes this effective is that I only learn something I'm actively interested in using for an actual project, instead of trying to force myself to learn a technology just because it's currently popular.
