### ISSUE TITLE
Hey c:

### ISSUE THREAD

**Issue by wazave** [taniarascia/ama#7]
How do you make time to work in all your posts/tutorials/projects? Do you have a job atm?

**Comment by taniarascia** [comment]
I do have a full-time job at the moment, and I've had a job in some capacity since I started. The website, articles, tutorials, and all my projects are the product of a long period of continuous work. It looks like a lot because it's a culmination of three or so years, but really it's only one or two posts a month with a few projects scattered in here and there.

Whatever you're doing, as long as you keep at it, it'll add up over a period of time.
