### ISSUE TITLE
How much time in average does it take for you to write a single blog post?

### ISSUE THREAD

**Issue by jeremymouzin** [taniarascia/ama#8]
I know it's a lot because I'm blogging too, but most people don't realize that. They all think that words just leak out from our fingers :-D.

**Comment by taniarascia** [comment]
Hi Jeremy, 

It's actually pretty difficult to quantify exactly how long it takes me to write an article, because it varies greatly depending on the article, and it depends on whether or not you take research into account.

The research is the part that takes the most amount of time. It's usually an entire day or two of studying, or playing around with whatever tool, process, framework, or concept I'm trying to learn. Once I have all the research and outlines done, I usually made a lot of notes and took a lot of pictures along the way - then it takes one full day of writing to finish. Once I start writing, I like to finish in a day if possible, sometimes two, but I don't want drafts sitting around unfinished so I try to get it done as quickly as possible.
