### ISSUE TITLE
What led you to begin writing guides?

### ISSUE THREAD

**Issue by seanpierce** [taniarascia/ama#9]
I stumbled upon your account by searching for the simplest, most straight forward way to whip up a php app connected to a SQL database. From there I saw the rest of your guides. They're great! What made you decide to do this?

**Comment by taniarascia** [comment]
Great question! I never knew I was going to be a top search result for a bunch of common web developer questions, or that I'd have access to helping so many people. I didn't know that I had any sort of technical writing talent before I began, so it wasn't really my plan.

Honestly, I was just so annoyed with the process of figuring out how to use Git when I didn't know anything about command line, ssh, and so on. Yet as I was trying to create, design, and develop, GitHub was everywhere. Repositories, commit, push, branch, so many terms I didn't understand and I just had no clue.
 When I finally figured it out, I didn't want anyone to suffer as I had, so I compiled everything I learned into one very short, sweet, succinct guide on what Git is, how to create a repository, and how to deploy the code to a production server with Git. 

I continued doing that every time I struggled with something. This website continues to be documentation for myself that just happens to help others. Every day I google something - `tania aws`, `tania vagrant`, `tania mac` - because I forget a process and I know where to find a good documentation.

Make something that fills a real need for yourself and likely others will come!
